modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/Ephys/mc-shulker-enchantments/issues"
[[mods]]
modId="shulker_enchantments"
version="${file.jarVersion}"
displayName="Shulker Enchantments"
updateJSONURL="https://mc-curse-update-checker.herokuapp.com/414163"
displayURL="https://github.com/Ephys/mc-shulker-enchantments"
logoFile="logo.png"
credits="FlandersAustin for the Logo <3"
authors="ephys"
description='''
This mod adds two enchantments for Shulker Boxes:
- The "Siphon" enchantment: Shulker Boxes enchanted with it will receive any picked up item, as long as the shulker box already has at least one
  item of the same type.
- The "Refill" enchantment: Shulker Boxes enchanted with automatically refill your main hand when you use an item that is included in the Shulker Box.
'''
[[dependencies.shulker_enchantments]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.shulker_enchantments]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.shulker_enchantments]]
    modId="curios"
    mandatory=false
    versionRange="[${curiosVersion},)"
    ordering="NONE"
    side="BOTH"
